name: Unit Tests
run-name: ${{ github.actor }} is running unit tests... 🚀
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        # Install pnpm
      - uses: pnpm/action-setup@v4
        name: Install pnpm 9
        with:
          version: 9.1.4

      # Install Node.js 20.x
      - name: Install Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      # Install dependencies, --frozen-lockfile is a default since pnpm 6.7.0
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
